chat_model_name: glm-5
embedding_model_name: qwen3-vl-embedding
embedding_fallback_model_name: qwen3-vl-embedding
oneapi_base_url: http://10.150.229.91:3000/v1
oneapi_api_key: "sk-7B2KMWlwG62Mb8Xw412a9eDb7f03444eB221C6878445D050"
